language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- bower install --silent
addons:
  sauce_connect: false
script:
- ./node_modules/.bin/polymer lint response-status-view.html
# - ./node_modules/.bin/polymer test --plugin sauce --job-name "response-status-view:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
    - stage
    - develop
after_success:
  - node tasks/ci.js
