/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   http-source-message-view.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

declare namespace ApiElements {

  /**
   * The element displays the HTTP source message that has been sent to the remote mchine.
   */
  class HttpSourceMessageView extends PolymerElement {

    /**
     * A HTTP message to display.
     */
    message: string|null|undefined;

    /**
     * True if the message is visible.
     */
    opened: boolean|null|undefined;

    /**
     * Toggles source message visibility
     */
    toggle(): void;

    /**
     * Computes icon name depending on `opened` state
     */
    _computeIcon(opened: Boolean|null): String|null;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "http-source-message-view": ApiElements.HttpSourceMessageView;
  }
}
