/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   response-redirects-panel.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

import {ResponseStatusMixin} from './response-status-mixin.js';

declare namespace ApiElements {

  /**
   * HTTP redirects info panel.
   * Renders list of redirects and headers in the response.
   */
  class ResponseRedirectsPanel extends
    ResponseStatusMixin(
    Object) {

    /**
     * List of redirects information.
     */
    redirects: any[]|null|undefined;

    /**
     * Computed value, `true` when `redirects` property is set and has value
     */
    readonly hasRedirects: boolean|null|undefined;

    /**
     * Computes 0-based index to 1-based number.
     */
    _computeIndexName(index: Number|null): Number|null;

    /**
     * Extracts a location URL form the headers.
     *
     * @param headers A HTTP headers string.
     * @returns A value of the location header or `unknown` if not
     * found.
     */
    _computeRedirectLocation(headers: String|null): String|null;
    _computeHasRedirects(record: any): any;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "response-redirects-panel": ApiElements.ResponseRedirectsPanel;
  }
}
